<?php

namespace App\Helpers;

class Constants {

	public const EXPIRE_CREDENTIALS = 4320000; // 50 days

	public const EXPIRE_MEDIA = 604800; // 1 week

	public const EXPIRE_HUMAN_CHECK = 315360000; // 10 years

	public const TITLE_MAX_LENGTH = 70;

	public const DESCRIPTION_MAX_LENGTH = 195;

	public const BROWSERS = [
		'115 Browser',
		'1stBrowser',
		'2345 Browser',
		'2345 Chrome',
		'2345 Explorer',
		'360 Secure Browser',
		'360 Speed Browser',
		'37abc',
		'7 Star',
		'ABrowse',
		'Acoo Browser',
		'Alienforce',
		'Aloha Browser',
		'Amigo',
		'Android',
		'Android WebView',
		'AOL Desktop',
		'AOL Shield',
		'APUSBrowser',
		'Arora',
		'Atomic Browser',
		'Avant',
		'Avast SafeZone',
		'Avira Scout',
		'Baidu Browser',
		'Baidu Browser HD',
		'Baidu Browser Mini',
		'Basilisk',
		'Battle.net Overlay',
		'Beaker',
		'Beamrise',
		'BlackBerry',
		'Blackberry Playbook Tablet',
		'Blackhawk',
		'Blazer',
		'Blue Browser',
		'Bowser',
		'Brave',
		'Browzar',
		'bumblebee',
		'Camino',
		'Cent Browser',
		'Charon',
		'Chedot',
		'Cheshire',
		'Chimera',
		'Chrome',
		'ChromePlus',
		'Chromium',
		'CM Browser',
		'CMUV DVBViewer',
		'Coc Coc Browser',
		'CometBird',
		'Conkeror',
		'CoolNovo',
		'Crazy Browser',
		'CTL',
		'Cunaguaro',
		'Cyberfox',
		'DBTEL',
		'Deepnet Explorer',
		'deg-degan Browser',
		'Diglo',
		'Diigo Browser',
		'Dillo',
		'DoCoMo',
		'Dolfin',
		'Dorado WAP Browser',
		'Doris',
		'Dragon',
		'DuckDuckGo Browser',
		'Edge',
		'Edge Mobile',
		'Element Browser',
		'Elements Browser',
		'ELinks',
		'Epic',
		'Epiphany',
		'ESATCOM',
		'Espial TV Browser',
		'EudoraWeb',
		'EZOS',
		'Fennec',
		'Firebird',
		'Firefox',
		'Firefox Focus',
		'Firefox for iOS',
		'FlameSky',
		'Flock',
		'Fluid',
		'FLY',
		'FlyFlow',
		'Foxconn',
		'Freebox Browser',
		'Galeon',
		'GEO',
		'Google Desktop',
		'GSPDA',
		'Haier',
		'Headless Chrome',
		'Headless Edge',
		'HS',
		'Huawei',
		'HuaweiBrowser',
		'Hyundai',
		'i-mobile',
		'i-mode Browser',
		'IAC',
		'iBall',
		'IBrowse',
		'iBrowser',
		'iCab',
		'iCab Mobile',
		'Iceape',
		'IceCat',
		'Icedove',
		'IceDragon',
		'Iceowl',
		'Iceweasel',
		'IE',
		'IEMobile',
		'iLunascape',
		'INNO',
		'Iridium Browser',
		'Iron',
		'Iron Mobile',
		'IXI',
		'Jasmine',
		'jBrowser',
		'jig browser web',
		'JUZI Browser',
		'K-Meleon',
		'K-Ninja',
		'Kazehakase',
		'kejian',
		'Kindle',
		'Kindle Fire',
		'Kinza',
		'Kiwi',
		'KKMAN',
		'Klondike',
		'KMLite',
		'KONKA',
		'Konqueror',
		'Kuaiso',
		'Lenovo',
		'LG',
		'LG Browser',
		'Liebao',
		'Liebao Fast',
		'Light',
		'Lightning',
		'Links',
		'lolifox',
		'Lovense Browser',
		'luakit',
		'Lunascape',
		'Lynx',
		'MAUI Wap Browser',
		'Maxon',
		'Maxthon',
		'Maxthon Nitro',
		'Mercator',
		'Mercury',
		'MicroB',
		'Midori',
		'Minimo',
		'Mint Browser',
		'Mitsu Browser',
		'Miui Browser',
		'Mobicip',
		'Mobile Safari UIWebView',
		'MobileExplorer',
		'MobileIron',
		'Tesla Car Browser',
		'Motorola Internet Browser',
		'Mozilla',
		'MStar Browser',
		'MultiZilla',
		'My Internet Browser',
		'Navigator',
		'NEC',
		'NetFront',
		'NetFront NX',
		'NetFrontLifeBrowser',
		'Netscape',
		'Neuron',
		'Nichrome',
		'Nintendo Browser',
		'noadsbrowser',
		'Nokia Browser',
		'Nokia Proxy Browser',
		'Ntent',
		'Obigo Q',
		'Oculus Browser',
		'Odyssey Web Browser',
		'OmniWeb',
		'OneBrowser',
		'open-webkit-sharp',
		'Openwave Mobile Browser',
		'OnePlus Browser',
		'Opera',
		'Opera Mini',
		'Opera Mobile',
		'Opera Neon',
		'Opera Touch',
		'Orca',
		'Oregano',
		'Origin',
		'Otter',
		'Overwolf Browser',
		'PaleMoon',
		'Palm Source',
		'Panasonic',
		'Panasonic TV Browser',
		'Pantech',
		'Phantom Browser',
		'PhantomJS',
		'Phoenix',
		'Pirate Browser',
		'Playstation',
		'Playstation Browser',
		'Polarity',
		'Prism',
		'PrivacyBrowser',
		'Puffin',
		'Qiyu Browser',
		'QQBrowser',
		'QQBrowser Mini',
		'Qt',
		'QtWebEngine',
		'QtWebkit',
		'QtWeb Browser',
		'QuickLook',
		'QupZilla',
		'qutebrowser',
		'QwantBrowser',
		'Qword Browser',
		'rekonq',
		'Roccat',
		'RockMelt',
		'Safari',
		'Sagem',
		'Sailfish Browser',
		'Saina',
		'Salam Browser',
		'Samsung',
		'Samsung Browser',
		'Samsung CrossApp',
		'Samsung Mobile Browser',
		'Samsung TV',
		'Samsung WebView',
		'SeaMonkey',
		'SEMC',
		'Seznam Browser',
		'Sharp',
		'Shiira',
		'Silk',
		'Skyfire',
		'Sleipnir',
		'SlimBoat',
		'SlimBrowser',
		'SlimerJS',
		'SlimJet Browser',
		'SmartTV WebBrowser',
		'SmartViera',
		'Sogou Explorer',
		'Sogou Mobile',
		'Sony',
		'SonyCEBrowser',
		'Sony PS2',
		'Sony PSP',
		'Sparrow',
		'Sputnik Browser',
		'Sraf',
		'Stainless',
		'Start Browser',
		'Sundance',
		'Sunrise',
		'SuperBird',
		'Surf Browser',
		'Swing',
		'Symphony Browser',
		'TazWeb',
		'Teleca-Obigo',
		'TenFourFox',
		'Tenta Browser',
		'TeslaBrowser',
		'Tevion',
		'TheWorld',
		'TinyBrowser',
		'Tizen Browser',
		'Tungsten Browser',
		'UC Browser',
		'UC Browser Mini',
		'UR Browser',
		'Vitelcom',
		'Vivaldi',
		'Vivo Browser',
		'Oppo Browser',
		'VmWare Browser',
		'Vodafone',
		'Vonkeror',
		'Voyager',
		'w3m',
		'Wahoo Browser',
		'WAP Browser',
		'Waterfox',
		'Web Explorer',
		'WebKit/webOS',
		'WebPirate Browser',
		'Weibo',
		'WeTab Browser',
		'Whale Browser',
		'WhiteHat Aviator',
		'WinWAP',
		'WKBrowser',
		'Wyzo',
		'Yandex Browser',
		'YaaniBrowser',
		'YOLO Browser',
		'YouWave Android on PC',
		'Zetakey Browser',
		'ZTE',
		'Zvu',
		'Ecosia',
		'HeyTapBrowser',
		'Meizu Browser',
	];

}
